use_frameworks!

platform :ios, '8.0'

target 'WGBEasyMarqueeView_Example' do
  pod 'WGBEasyMarqueeView', :path => '../'

  target 'WGBEasyMarqueeView_Tests' do
    inherit! :search_paths

    
  end
end
